name: reveal-pdf
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build PDF
        run: docker run --rm -t -v `pwd`:/slides -v ~:/home/user astefanutti/decktape ./index.html tecaj.pdf

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: prosojnice
          path: slides/tecaj.pdf
