name: reveal-pdf
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - uses: actions/checkout@v3

      - name: Create "/slides" directory
        run: mkdir slides && sudo chmod 777 slides

      - name: Build PDF
        run: docker run --rm -t -v `pwd`:/slides -v ~:/home/user astefanutti/decktape https://jakobkordez.github.io/ham-tecaj/ slides/tecaj.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: slides
          path: slides/tecaj.pdf

      - name: Create release
        uses: actions/checkout@v2
        with:
          artifacts: "slides/tecaj.pdf"
