name: reveal-pdf
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - name: Create "slides" directory
        run: mkdir slides && sudo chmod 777 slides

      - name: Save as PDF
        uses: jakobkordez/web_to_pdf_action@patch-useScreen
        with:
          webPageURL: https://jakobkordez.github.io/ham-tecaj/?print-pdf
          outputFile: slides/tecaj.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"width": "1280", "height": "720"}'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: slides
          path: slides/tecaj.pdf

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "slides/tecaj.pdf"
